apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rob-test-app
  title: Rob Test App
  description: Test Application
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - typescript
    - backstage
spec:
  type: website
  owner: guests
  lifecycle: experimental
