name: Repository Events
on: [push, pull_request, issues]

jobs:
    checkout-test:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo $GITHUB_SHA
                echo $GITHUB_REF
            - name: List files before
              run: ls -al
            - uses: actions/checkout@v4
            - name: List files after
              run: ls -al
